fs_dict_single = {
    'N_NN': 'n',
    'N_NNP': 'n',
    'N_NST': 'nst',
    'PR_PRP': 'pn',
    'PR_PRF': 'pn',
    'PR_PRL': 'pn',
    'PR_PRC': 'pn',
    'PR_PRQ': 'pn',
    'DM': 'pn',
    'DM_DMD': 'pn',
    'DM_DMR': 'pn',
    'DM_DMQ': 'pn',
    'V_VM': 'v',
    'V_VM_VF': 'v',
    'V_VM_VNF': 'v',
    'V_VM_VINF': 'v',
    'V_VM_VNG': 'v',
    'N_NNV': 'n',
    'V_VAUX': 'v',
    'CC': 'avy',
    'CC_CCD': 'avy',
    'CC_CCS': 'avy',
    'CC_CCS_UT': 'avy',
    'RP_RPD': 'avy',
    'RP_CL': 'n',
    'RP_INJ': 'adj',
    'RP_INTF': 'adj',
    'QT_QTF': 'adj',
    'QT_QTC': 'num',
    'QT_QTO': 'num',
    'RD_RDF': 'unk',
    'RD_SYM': 'punc',
    'RD_PUNC': 'punc',
    'RD_UNK': 'unk',
    'RD_ECH': 'n',
    'JJ': 'adj',
    'RB': 'adv',
    'PSP': 'psp',
    'RP_NEG': 'avy',
    'PR_PRI':'pn',
    'DM_DMI':'pn',
    'RD_BUL':'unk'
}

fs_dict_double = {
    'N__NN': 'n',
    'N__NNP': 'n',
    'N__NST': 'nst',
    'PR__PRP': 'pn',
    'PR__PRF': 'pn',
    'PR__PRL': 'pn',
    'PR__PRC': 'pn',
    'PR__PRQ': 'pn',
    'DM': 'pn',
    'DM__DMD': 'pn',
    'DM__DMR': 'pn',
    'DM__DMQ': 'pn',
    'V__VM': 'v',
    'V__VM__VF': 'v',
    'V__VM__VNF': 'v',
    'V__VM__VINF': 'v',
    'V__VM__VNG': 'v',
    'N__NNV': 'n',
    'V__VAUX': 'v',
    'CC': 'avy',
    'CC__CCD': 'avy',
    'CC__CCS': 'avy',
    'CC__CCS_UT': 'avy',
    'RP__RPD': 'avy',
    'RP__CL': 'n',
    'RP__INJ': 'adj',
    'RP__INTF': 'adj',
    'QT__QTF': 'adj',
    'QT__QTC': 'num',
    'QT__QTO': 'num',
    'RD__RDF': 'unk',
    'RD__SYM': 'punc',
    'RD__PUNC': 'punc',
    'RD__UNK': 'unk',
    'RD__ECH': 'n',
    'JJ': 'adj',
    'RB': 'adv',
    'PSP': 'psp',
    'RP__NEG': 'avy',
    'PR__PRI':'pn',
    'DM__DMI':'pn',
    'RD__BUL':'unk'
}

